### ISSUE TITLE
setting appveyor_repo_tag in tic::deploy

### ISSUE THREAD

**Issue by yonicd** [ropenscilabs/tic#100]
How do I set `appveyor_repo_tag` to false in `appveyor` using `tic`?

I can see that `tic` is checking for a tag, but can see where to toggle it off so it deploys regardless of a tag (to gh-pages in this case)

even if there is a tag i can not get it to deploy back to the github repo.

[appveyor.yml](https://github.com/yonicd/covrpage/blob/appveyor/appveyor.yml)
[tic.R](https://github.com/yonicd/covrpage/blob/appveyor/tic.R)
[appveyor log](https://ci.appveyor.com/project/yonicd/covrpage#L616)

thanks

**Comment by pat-s** [comment]
I don't think you can set env variables on appveypr with _tic_ atm. Try the following:

In `appveyor.yml` set

```yml
install:
  - cmd: R -q -e "Sys.setenv('appveyor_repo_tag' == 'true')"
```

**Comment by krlmlr** [comment]
Environment variables need to be defined in `appveyor.yml` .

**Comment by pat-s** [comment]
> Environment variables need to be defined in appveyor.yml .

:man_facepalming: 	Why did I make it so complicated? :laughing: 	

```yml
environment:
  appveyor_repo_tag: TRUE
```

should also work then.

**Comment by yonicd** [comment]
I'll try that again. I think at one point I did that and it still wouldn't budge.

**Comment by krlmlr** [comment]
Closing for now, please open a new issue if problems persist.
