### ISSUE TITLE
Auto-detect Bioconductor pkgs

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#101]
To ensure deps are properly detected and installed.

`BiocManager::available()` lists all Bioconductor pkgs. 
We could do a diff of all required deps and then optionally call `BiocManager::install()`.

In addition, we should add a `step_install_bioconductor()` step similar to `step_install_cran()`.

**Comment by pat-s** [comment]
Maybe expanding the `repos` option in `remotes::install_deps()` will do it: https://github.com/ropenscilabs/tic/commit/4951b8abb90b436e74c5d5556cc90e4f1fa12b16

**Comment by pat-s** [comment]
Looks good here: https://travis-ci.org/mlr-org/mlr/jobs/455216334#L2916

Any concerns @krlmlr?

**Comment by krlmlr** [comment]
Better manually, as part of `step_install_deps()` (https://github.com/ropenscilabs/tic/issues/74#issuecomment-478374653).

**Comment by pat-s** [comment]
@krlmlr Should we use `repos = c(getOption("repos"), remotes::bioc_install_repos()))` as the default in `step_install_deps()`?

I see a lot of headaches for people facing rev deps of Biocondutor packages trying to find this "repo" adjustment.

Is there any possible downside I might be overlooking here?

**Comment by pat-s** [comment]
@krlmlr Should we use `repos = c(getOption("repos"), remotes::bioc_install_repos()))` as the default in `step_install_deps()`?

I see a lot of headaches for people facing rev deps of Biocondutor packages trying to find this "repo" adjustment.

Is there any possible downside I might be overlooking here?
