### ISSUE TITLE
Exclude r-base pkgs from being updated in every build

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#102]
When preparing `step_rcmdcheck()` we update all pkgs by doing

https://github.com/ropenscilabs/tic/blob/2db92f6b36e4059d83335e0c59a5998373eff95e/R/steps-rcmdcheck.R#L12-L16

However, all the base pkgs (mgcv, lattice, foreign) get updated on every build because they will be reset by the R-installer in every build to the version of the latest R version release. 
Example: https://travis-ci.org/mlr-org/mlr3/builds/452328643#L931

This is really annoying. Usually users do not need the latest version of these pkgs for their pkgs. 
Would it be better it we would replace the call above with 

```r
installed_packages <- installed.packages()[, "Package"]
remotes::update_packages(setdiff(installed_packages, 
  c("Matrix", "survival", "mgcv", "lattice")))
```

https://github.com/r-lib/remotes/issues/241

**Comment by krlmlr** [comment]
@jimhester: How often are the R binary archives used on Travis updated?

**Comment by jimhester** [comment]
The R-devel binary is updated hourly, the rest are not updated after they are released.

**Comment by pat-s** [comment]
This sounds like we need to account for it to save build time between the releases.

**Comment by krlmlr** [comment]
@jimhester: Would you consider daily updates of the binaries for non-devel releases?

**Comment by jimhester** [comment]
No, why would I want to do this?

**Comment by krlmlr** [comment]
To have all packages up to date by default? This is similar to the idea we discussed at rstudio::conf() -- a zip file of preinstalled frequently used packages -- a copy of the R-recommended packages could sit there too.

I guess we need to work around now either way.

**Comment by pat-s** [comment]
AFAIR we decided to not update the r-base/rec pkgs unless they are explicitly used in the DESC? At least I haven't seen this issue being important in the last year. Closing for now.
