### ISSUE TITLE
converting tic.R and travis.yml to a single travis.yml

### ISSUE THREAD

**Issue by yonicd** [ropenscilabs/tic#109]
is there a non-exported function that the inputs are the `travis.yml` and the `tic.R` and the output is the combined `travis.yml` file that travis actually runs. This would make clear what travis will actually run in the end, clearing up some of the initial "
black box" feeling for new users.

**Comment by pat-s** [comment]
The actions are redirected from `.travis.yml` to `tic.R`. In `tic.R` plain R functions are called to execute all the action.

These functions from the _tic_ pkg query certain env variables from the build and then schedule the execution order into stages and steps. 

There is not combined `.travis.yml` file. The `.travis.yml` file is not more than a settings file that specifies which command line functions are executed in a certain order (stages).

The goal of _tic_ is to make `.travis.yml` obsolote and specify _any_ action in `tic.R`. The advantage of `tic.R` is its flexibility, i.e. not being limited to certain settings that are valid in `.travis.yml` (or other CI YAML files).

**Comment by yonicd** [comment]
still, for people who are use to yml, making the case for transitioning would be easier if the bridge could be in some way made.

Is there a way to unfurl all the steps that are internally ordered in tic and list them in order, ie first this will happen, then this will happen, so and so forth?

**Comment by pat-s** [comment]
> Is there a way to unfurl all the steps that are internally ordered in tic and list them in order, ie first this will happen, then this will happen, so and so forth?

See https://deploy-preview-80--wonderful-volhard-261e08.netlify.com/articles/build-lifecycle.html for a WIP.

**Comment by yonicd** [comment]
very cool. that is the intended use chain of triggers. what if i create my own chain. How can I see the order that tic runs them in, in practice?

**Comment by maelle** [comment]
A further advantage of being able to get the combined Travis config would be to be able to opt out of `tic` later :speak_no_evil:

**Comment by krlmlr** [comment]
We have `tic::run_all_stages()`, it might be possible to include a call to this function in the `script` stage of `.travis.yml` . Is this what you're asking for?

**Comment by pat-s** [comment]
> We have tic::run_all_stages(), it might be possible to include a call to this function in the script stage of .travis.yml . Is this what you're asking for?

AFAIU the question is whether its possible to combine `tic.R` and `.travis.yml` into ONE single file instead of having two.

**Comment by yonicd** [comment]
a different way of asking this. is tic.R being converted under the hood to yml bash calls? if so can that be mocked within R to create a valid yml file? This is not meant to replace the api {tic} uses, but so make it more transparent what is the sequence of bash call being run.

**Comment by pat-s** [comment]
> a different way of asking this. is tic.R being converted under the hood to yml bash calls? 

No, we forward the Travis stages to call R code which is then being executed in the respective container that Travis is running. 
Parsing it back to Travis Syntax would completely contradict the idea of the package which is being CI-agnostic (by porting the CI specific syntax to R calls.)

I do not see any possibility to support this idea based on how everything is linked together. But maybe @krlmlr can jump in here and clarify :)

**Comment by yonicd** [comment]
i'm not asking to contradict how the package works. i was asking if the stages could be listed out in sequential form in the same sequence travis is seeing them as a merge between travis.yml and tic.R. It would clarify what is being run and when. it may seem silly to ask for, but it would really help new users to feel comfortable with the black box feeling imo.

**Comment by pat-s** [comment]
In master we have `dsl_load()` and `dsl_get()` since a few days. Does that help?

**Comment by yonicd** [comment]
not sure what i'm seeing here

<details open>
<summary> <span title='Click to Expand'> tic.covrpage/tic.R </span> </summary>

```r
add_package_checks()

if (Sys.getenv("id_rsa") != "") {
# pkgdown documentation can be built optionally. Other example criteria:
# - `inherits(ci(), "TravisCI")`: Only for Travis CI
# - `ci()$is_tag()`: Only for tags, not for branches
# - `Sys.getenv("BUILD_PKGDOWN") != ""`: If the env var "BUILD_PKGDOWN" is set
# - `Sys.getenv("TRAVIS_EVENT_TYPE") == "cron"`: Only for Travis cron jobs
get_stage("before_deploy") %>%
  add_step(step_setup_ssh())

get_stage("deploy") %>%
  add_code_step(covr::codecov())%>%
  add_code_step(print(Sys.getenv('TRAVIS_COMMIT_MESSAGE')))

covrpage_flag <- '\\[\\s*(skip\\s+covrpage|covrpage\\s+skip)\\s*\\]'

if(!grepl(covrpage_flag,Sys.getenv('TRAVIS_COMMIT_MESSAGE'))){
  get_stage("deploy") %>%
    add_code_step(devtools::install())%>%
    add_code_step(
      covrpage::covrpage_ci(update_badge = FALSE),
      prepare_call = remotes::install_github("metrumresearchgroup/covrpage")
    ) %>%
    add_step(step_push_deploy(commit_paths = "tests/README.md"))
}
}
```

</details><br>

```r
> tic::dsl_load(path = 'tic.R')
✔ Loading tic stage configuration from tic.R
Warning message:
'add_package_checks' is deprecated.
Use 'do_package_checks' instead.
See help("Deprecated") 
> tic::dsl_get()
── install ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── stage ──
── install ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── stage ──
▶ step_install_deps(repos = repos)
── script ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── stage ──
── script ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── stage ──
▶ step_rcmdcheck(warnings_are_errors = warnings_are_errors, notes_are_errors = notes_are_errors, 
    args = args, build_args = build_args, error_on = error_on, 
    repos = repos, timeout = timeout)
```

<details closed>
<summary> <span title='Click to Expand'> session info </span> </summary>

```r
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       macOS  10.14.4              
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2019-05-03                  

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version     date       lib source                             
 assertthat    0.2.1       2019-03-21 [1] CRAN (R 3.5.1)                     
 backports     1.1.4       2019-04-10 [1] CRAN (R 3.5.2)                     
 cli           1.1.0       2019-03-19 [1] CRAN (R 3.5.1)                     
 clipr         0.5.0       2019-01-11 [1] CRAN (R 3.5.2)                     
 crayon        1.3.4       2017-09-16 [1] CRAN (R 3.5.0)                     
 details       0.0.51      2019-04-04 [1] local                              
 digest        0.6.18      2018-10-10 [1] CRAN (R 3.5.0)                     
 magrittr      1.5         2014-11-22 [1] CRAN (R 3.5.0)                     
 memoise       1.1.0       2017-04-21 [1] CRAN (R 3.5.0)                     
 packrat       0.4.9-3     2018-06-01 [1] CRAN (R 3.5.0)                     
 R6            2.4.0       2019-02-14 [1] CRAN (R 3.5.2)                     
 rlang         0.3.4       2019-04-07 [1] CRAN (R 3.5.2)                     
 rstudioapi    0.10.0-9000 2019-03-22 [1] Github (rstudio/rstudioapi@7038aee)
 sessioninfo   1.1.1       2018-11-05 [1] CRAN (R 3.5.0)                     
 tic           0.2.13.9015 2019-05-03 [1] local                              
 withr         2.1.2       2018-03-15 [1] CRAN (R 3.5.0)                     

[1] /Users/yonis/Library/R/3.5/library
[2] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

</details><br>

**Comment by pat-s** [comment]
> i'm not asking to contradict how the package works. i was asking if the stages could be listed out in sequential form in the same sequence travis is seeing them as a merge between travis.yml and tic.R. It would clarify what is being run and when.

I guess I still thought you want to combine both files in general, i.e. getting rid of `tic.R`.

> not sure what i'm seeing here

You see the stages and step that are being run.
Actually you should see some additional stages (like "deploy" and "before_deploy"). These might now show up because they are only run conditionally. We should fix this.

But is the concept now clear? Or what am I missing here? Does https://ropenscilabs.github.io/tic/articles/build-lifecycle.html help?

**Comment by yonicd** [comment]
i was confused by not seeing all the steps in from the tic.R file. that makes sense if they were there.

i didnt see on the rhs of the line rules ( "stage" )

is each line an action? what is the difference between the first install and the second install? first script and second script?

```
> tic::dsl_get()
── install ....── stage ──
── install ....── stage ──
▶ step_install_deps(repos = repos)
── script ....── stage ──
── script ....── stage ──
▶ step_rcmdcheck(warnings_are_errors = warnings_are_errors, notes_are_errors = notes_are_errors, 
    args = args, build_args = build_args, error_on = error_on, 
    repos = repos, timeout = timeout)
```

**Comment by pat-s** [comment]
> i didnt see on the rhs of the line rules ( "stage" ). that should be the width of the output, right?

Yes, usually that should work. This is done automatically by the _cli_ pkg.

> is each line an action? what is the difference between the first install and the second install? first script and second script?

Each step is an action.
Currently steps will appear twice if they are added by multiple macros. We are aware of it (#145)

**Comment by pat-s** [comment]
I don't think the initial purpose of this issue still applies. Hence I'll close here.

Also to summarise:

We are not planning on combining the actions from the travis yml and the tic steps into one file which is then being executed on the CI provider.
We are providing templates for various CI providers with predefined settings (R-Version, architecture, etc) which are then combined with the specific actions of _tic_ (install. dependencies, R CMD check, pkgdown build & deploy).
