### ISSUE TITLE
There is no `usethis::use_ci()` 

### ISSUE THREAD

**Issue by adamhsparks** [ropenscilabs/tic#111]
Using the README as a starting point, I attempted to use `usethis::use_ci()`, however `Error: 'use_ci' is not an exported object from 'namespace:usethis'` is returned.

Not sure what the proper replacement is for it?

**Comment by adamhsparks** [comment]
Can do that

-- 
Adam H Sparks

**Comment by pat-s** [comment]
We aim to merge the updated documentation soon, stay tuned!

**Comment by zkamvar** [comment]
Hi,

Is there any update on this? [The documentation](https://ropenscilabs.github.io/tic/articles/tic.html) still suggests to use `usethis::use_ci()`, but the recent release does not include this function, but it does include `usethis::use_tidy_ci()`, but does not appear to set anything up with tic.

**Comment by pat-s** [comment]
You're right. This is because `usethis` decided not to incorporate the _tic_ idea. You can use `travis::use_tic()` for now. Soon the function will live in `tic::use_tic()`. We are still in a beta state with ongoing changes. We're aiming to have a CRAN release soon.

**Comment by zkamvar** [comment]
Thank you. I think my confusion came from the fact that installing tic by the normal route does not install `ropenscilabs/travis` by default (as it's in suggests), so I thought `travis::use_tic()` may have been a typo.

**Comment by hongyuanjia** [comment]
The same confusing came to me too. Have to manually install `ropenscilabs/travis` first.

**Comment by pat-s** [comment]
@krlmlr Should we think about moving _travis_ to IMPORTS? Guess this problem will come up more often if users are using the setup wizard.

**Comment by krlmlr** [comment]
{travis} can't be in `Imports`, we'd be dragging it along for each and every CI run. The message should be clear enough.
