### ISSUE TITLE
Is any example about shiny or flexdashboard CI?

### ISSUE THREAD

**Issue by harryprince** [ropenscilabs/tic#112]

**Comment by krlmlr** [comment]
I don't have any such example, but I'd be happy to include one. What would the CI process for a flexdashboard look like?

**Comment by harryprince** [comment]
`shinytest` package can test shiny with context including screenshot level.

**Comment by krlmlr** [comment]
Would you like to contribute an example, similar to https://github.com/metrumresearchgroup/tic.covrpage and the examples listed on https://ropenscilabs.github.io/tic/#examples?

**Comment by harryprince** [comment]
might be ask RStudio staff directly is best option.

**Comment by krlmlr** [comment]
I'm happy to link to an example, but I don't have the capacity to implement one myself.
