### ISSUE TITLE
example repo for tic.coverpage

### ISSUE THREAD

**Issue by yonicd** [ropenscilabs/tic#114]
i am interested in adding an example repo of how to use tic and covrpage as an alternative to the PR that @pat-s created.

i see that all the the ones in the readme are repos that are within ropensci. would it be better to have a tic.covrpage in ropensci or it does not matter?

**Comment by krlmlr** [comment]
Thanks, very much appreciated! Can you please start in your own repo and we can later move to ropensci(labs)?

**Comment by yonicd** [comment]
Is there a `tic` example of parsing the commit message that is passed to the CI envir?

**Comment by krlmlr** [comment]
None I'm aware of. I don't understand "parsing the commit message".

Can you use the `git2r` package to retrieve the log message of the latest commit? Or are you looking for the `commit_message` argument to `step_do_push_deploy()`?

**Comment by yonicd** [comment]
yes, i want to add a clause to use so covrpage doesnt get pushed back blindly to the master/dev-branch

eg

commit message would be `updated something in repo [covrpage]`

**Comment by yonicd** [comment]
can i use git2r? i would want to query on the CI the message not on the local machine.

**Comment by yonicd** [comment]
maybe [this](https://github.com/travis-ci/travis-ci/issues/8861#issuecomment-349037474) is the solution

**Comment by yonicd** [comment]
i forked the example repo to my user where the permissions are easier to set up the ssh.  

looks like the example tic/travis works as expected.

https://github.com/yonicd/tic.covrpage
https://travis-ci.org/yonicd/tic.covrpage

**Comment by krlmlr** [comment]
Thanks! Would you like to transfer the repo to _ropenscilabs_, or keep it in your namespace? Either option works for me.

**Comment by yonicd** [comment]
I think that transferring it over to ropenscilabs will be easiest thing to do. thanks again!

**Comment by yonicd** [comment]
How do I transfer the repo into ropenscilabs? I dont have permissions for that.

**Comment by pat-s** [comment]
@maelle can you help here?

**Comment by maelle** [comment]
@yonicd I've now invited you to the ropenscilabs org so you can transfer the repo, thank you!

**Comment by yonicd** [comment]
transferred the fork i had the ssh key working on. i'm guess that the ssh key needs to be reset @krlmlr ?

thanks @maelle 	!

**Comment by maelle** [comment]
I'll add your admin rights back @yonicd

**Comment by yonicd** [comment]
thanks @maelle

**Comment by krlmlr** [comment]
Thanks. Does it work now? Can we add a link to `tic.Rmd` and perhaps to the README?

**Comment by yonicd** [comment]
worked last time i checked.
