### ISSUE TITLE
repo with different package folders

### ISSUE THREAD

**Issue by jwijffels** [ropenscilabs/tic#117]
I'm trying out this package to see if I can publish automatically to a drat repo. 
For this github repo which contains currently 7 R package folders https://github.com/bnosac/image
I'm getting the error that there is no DESCRIPTION file (https://travis-ci.org/bnosac/image/jobs/488569507) that's because they are all in subfolders of the main repo.
How do I set it up such that I can do the R CMD check on the different subfolders using this tic framework.
thanks!

**Comment by jwijffels** [comment]
Ok, finally got this to work after a day of debugging. Things that were not clear:
- I had to set manually GITHUB_PAT in appveyor / travis / github
- Same for id_rsa 
- I had to create id_rsa myself using openssl as travis::use_tic() did not do this
- the package does not work if there is no DESCRIPTION file in the root folder
- not does it handle R packages with subfolders, so I had to split out the step_add_to_drat in different steps manually
- I needed to push to the branch gh-pages instead of to the master, giving issues
In case anyone bumps into this thread: package is here where the CI flows are set up https://github.com/bnosac/image and the drat is here https://github.com/bnosac/drat

**Comment by krlmlr** [comment]
Thanks for providing this guidance.

Currently, so many tools assume that each repo contains only one package/projects/..., that it's easier for this project to impose this limitation.

**Comment by jwijffels** [comment]
Sure, no problem. You are the maintainer, you make the shots.
