### ISSUE TITLE
Prepare review

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#120]
- Legible output, perhaps with {cli}
    - [x] setup (#153)
    - [x] regular processing of steps
    - [x] error output (#105)
    - [x] display of workflow (#77)
- [x] remove usethis from docs
- [x] move templates from {travis} to here, and tweak (#81)
	- `detect_repo_type()`, `use_travis_yml()`, `use_appveyor_yml()`, `use_tic_r()`
- [x] package name (#72)
- [x] templates (#154)

**Comment by krlmlr** [comment]
I think we're good to go here. I'll take a final look at the documentation soon -- are you familiar with the rOpenSci review process?

**Comment by pat-s** [comment]
> are you familiar with the rOpenSci review process?

No, no exp yet.

**Comment by krlmlr** [comment]
Submitted for review.
