### ISSUE TITLE
Rename add_package_checks()

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#123]
and move to a separate help page.

All macros should have a prefix different from `add_`. Current suggestion: `do_`, still looking for alternatives.

**Comment by pat-s** [comment]
Should we have separate help pages for each macro? Even combining only `add_package_checks()` and `do_pkgdown_site()` (names should still change) makes the help page quite messy.

**Comment by krlmlr** [comment]
Not sure, maybe a separate section for the details that describe each macro?

**Comment by pat-s** [comment]
If we keep the Description section as it is now, this won't change much. And moving all information specifically to a dedicated section for each macro is tedious.

I also think that "DSL" in combination with "tics domain specific language" is not easy to understand for most users (referring to the current help page title and index).

I'll first rename `add_package_checks()` to `do_package_checks()`?

**Comment by krlmlr** [comment]
Sure, let's look at documentation in a separate step.

**Comment by krlmlr** [comment]
Closed by #128.
