### ISSUE TITLE
How about adding a community supported "R-tic" to travis?

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#127]
Did you already consider this in the past? https://docs.travis-ci.com/user/languages/community-supported-languages/#adding-a-new-language

Or maybe even simpler, add a config option to the existing one (https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb) that sets all the subsequent steps to what we need in `tic`.

Following this logic, a `.travis.yml` using the tic-r "backend" could look like 

```yml
language: r
tic: true

```

And would just automatically forward everything to `tic.R` which then only consists of macros (in the optimal case).

Edit: I see #15 is related.

**Comment by krlmlr** [comment]
Haven't considered a new language before. Let's revisit after CRAN release.

**Comment by pat-s** [comment]
I would prefer to just ask if we can add an option "tic" and then condition the following steps on it, mutating these to our needs:

https://github.com/travis-ci/travis-build/blob/cdab8ecb26bb2b7f13fb6eaa0bbd315f5d453d0d/lib/travis/build/script/r.rb#L216-L243

Then we would in fact only need to specify 

```yml
language: r
tic: true
```

and all stages are automatically linked to `tic.R`.

**Comment by pat-s** [comment]
It would be really great if users could start right-away with an empty Travis yml, i.e doing it before we release to CRAN. Should we try asking Jim in the next days? If this would be accepted it would not be that much work to adapt the code to insert the `tic`-based conditions into the r-language build script. 

Also it would be a one-time task and since we just forward all stages we should in theory never have to touch it again / maintain.

**Comment by krlmlr** [comment]
Done. Closing in favor of #15.
