### ISSUE TITLE
Add argument "document" to do_package_checks()

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#132]
Because compiled packages need another `devtools::document()` step before building a pkgdown site or doing R cmd check since `roxygen2` >= 6.1.1.

Otherwise all compiled packages cannot use the macro (e.g. mlr).

**Comment by krlmlr** [comment]
Can you craft a reprex? I don't think we should ever call `document()` automatically, and I also think there must be a way to fix the problem upstream.

**Comment by pat-s** [comment]
All information is in here: https://github.com/klutometis/roxygen/issues/822

The first post outlines the problem in a Travis build.

**Comment by krlmlr** [comment]
I think https://github.com/r-lib/pkgload/issues/82 would fix that, but we need a reprex to be sure.

**Comment by pat-s** [comment]
For mlr we even do this:

```r
add_code_step(pkgbuild::compile_dll()) %>%
add_code_step(devtools::document()) %>%
```

I'll spin up a test branch.

**Comment by krlmlr** [comment]
Test branch -- of {mlr}? I think a minimal example would be very useful, seems it has been missing so far from the related discussions or I haven't looked enough.

**Comment by pat-s** [comment]
Yes. Looks good so far with the default approach: https://travis-ci.org/mlr-org/mlr/jobs/517470098

Looks like false-alarm. Sorry for the bells.
