### ISSUE TITLE
ci_is_tag() prevents deployment

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#141]
Build: https://travis-ci.org/ropenscilabs/tic/jobs/519758834#L1391

https://github.com/ropenscilabs/tic/blob/a9da3f9501501438601a1e710e26eaa63c1c5a72/R/steps-git.R#L208

@krlmlr Any idea why this happens?

**Comment by krlmlr** [comment]
Perhaps the `get_tag()` implementation in the `TravisCI` class?

https://github.com/ropenscilabs/tic/blob/a9da3f9501501438601a1e710e26eaa63c1c5a72/R/travis.R#L10-L12

**Comment by pat-s** [comment]
Ah yes, bc `self$has_env("TRAVIS_TAG")` returns TRUE but we actually need the env name..
