### ISSUE TITLE
Muddled windows paths on step_add_to_drat()

### ISSUE THREAD

**Issue by zkamvar** [ropenscilabs/tic#149]
I'm having a weird problem. I'm trying to follow the examples and recreate https://github.com/ropenscilabs/tic.drat (https://github.com/zkamvar/tic.drat) and https://github.com/ropenscilabs/tic.drat.repo (https://github.com/zkamvar/tic.drat.repo)

I've been able to successfully deploy from travis (:tada:), but I keep running into [the following warning on appveyor](https://ci.appveyor.com/project/zkamvar/tic-drat/builds/23919783#L414):

```
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\Users\appveyor\Documents/git/drat/bin/windows/contrib/3.5": The system cannot find the path specified
```

It appears that the tilde is being expanded with windows slashes, but `file.path()` doesn't know how to handle the case when you are combining the two. 

When I look at the [traceback on a build that treated warnings as errors](https://ci.appveyor.com/project/zkamvar/tic-drat/builds/23919466#L299), I find that this confusion originates in `drat::insertPackage()`, but I'm not quite sure how to stop it from happening. I've attempted to [hard-code the path using normal forward slashes to no avail](https://ci.appveyor.com/project/zkamvar/tic-drat/builds/23920524) and I've hit a wall.

**Comment by krlmlr** [comment]
Can you try [an RDP connection into AppVeyor](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/), or perhaps running `tic::run_all_stages()` on a Windows machine?

**Comment by zkamvar** [comment]
I will look into this, but probably won't be able to get to it until tuesday

**Comment by pat-s** [comment]
Stale
