### ISSUE TITLE
Shortcuts for testing if on a specific CI

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#150]
`ci_is_travis()` would be true only on Travis CI.

**Comment by pat-s** [comment]
To use this for conditional default args of `step_rcmdcheck()` (see https://github.com/ropenscilabs/tic.package/pull/3#issuecomment-487109120), we need a way to allow multiple constructors for class `RCMDCheck`.

[This SO post](https://stackoverflow.com/questions/35025953/r-how-to-define-multiple-constructors-for-an-r6-class) shows how.

Do we want to go this way? I do not see another option currently with the aim of preserving a single `step_rcmdcheck()` function for the user. 

The documentation would then list both constructors.

**Comment by pat-s** [comment]
Happy to have your thoughts/help on this PR.

**Comment by krlmlr** [comment]
Not sure I follow. I'd rather say:

```
step_rcmdcheck <- function(..., build_args = NULL) {
  if (is.null(build_args)) {
    if (is_windows()) {
      build_args <- c("--no-manual", "--no-vignettes", ...) # ???
    } else {
      build_args <- c("--no-manual", ...)
    }
  }
}
```

**Comment by krlmlr** [comment]
We could expose `ci_get_default_build_arg()` and `ci_get_default_check_arg()` methods too.

**Comment by pat-s** [comment]
Overlooked this easy way and made it way too complicated.

Even if the default value of `build_arg` is set to NULL, we can simply list the CI specific defaults in the param description. Easy and simple.
Conditional constructors are not really needed here :smile: 

I'm away until the evening. If you're keen on continuing here, feel free to :)
