### ISSUE TITLE
Update linked example projects

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#154]
- [x] Review https://github.com/ropenscilabs/tic.package/pull/3, double-check if templates here need to be adapted and if we need to change the default of `build_args` in `step_rcmdcheck()`
- [x] Use new `.travis.yml` and `appveyor.yml` templates in all projects
- [x] edit `tic.R` to reflect new changes

The PRs that are currently open are a starting point, but need more tweaks.

**Comment by pat-s** [comment]
Templates are updated.

- bookdown and covrpage badges will change after the next CRON run (removed the forks, created clean repos)
- the examples for which appveyor is failing are related to pandoc missing and should be solved with https://github.com/ropenscilabs/tic/pull/157
- examples now use the new macros if possible

**Comment by krlmlr** [comment]
Do I need to review anything?

**Comment by pat-s** [comment]
- Updated all templates (installing with `remotes::install_cran()` needs ofc be done later)
- Sorted the examples in the tic README
- fixed the appveyor badges
- harmonized the READMEs of all examples

Please take a brief look - a second pair of eyes might always spot some leftovers.

**Comment by krlmlr** [comment]
Aligned templates, tweaked AppVeyor badges, skimmed over READMEs. Enabling AppVeyor for all repos is nice, but not sure how useful since deployment is brittle.

Thanks for working on this!

**Comment by pat-s** [comment]
> Enabling AppVeyor for all repos is nice, but not sure how useful since deployment is brittle.

It's just for completeness. Even if some are failing, leaving some out for Appveyor specifically might raise questions.
