### ISSUE TITLE
Coloring of steps is not preserved across linebreaks

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#155]
See https://travis-ci.org/ropenscilabs/tic/jobs/525248438#L1010

**Comment by krlmlr** [comment]
What a charming, cute little glitch! It *could* be on purpose too ;-)

**Comment by pat-s** [comment]
I notice everything :stuck_out_tongue:

**Comment by pat-s** [comment]
investment/return ration in fixing this is not given I'd say ...
