### ISSUE TITLE
`dsl_get()`: No steps defined in any stage

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#164]
Running `dsl_get()` often only returns

```sh
tic::dsl_get()
✔ Creating a blank tic stage configuration
ℹ No steps defined in any stage
```

Even when running `dsl_load()` before. 

In a repo with a `tic.R` file.

This happens more often than the actual behavior (printing out the steps).

**Comment by krlmlr** [comment]
Closing as duplicate.

**Comment by pat-s** [comment]
It is not dup I think. This issue relates to the fact, that `dsl_get()` returns only the empty storage that is created when calling `dsl_get()` locally.
Calling `dsl_load(force = TRUE)` is required to reload the local `tic.R` configuration.

#### Questions

- Why is `dsl_init()` exported? Has it any value for the user or should we make it internal?
- Can we call `dsl_load(force = TRUE)` if we have class `MockCI`? I.e. running locally

**Comment by krlmlr** [comment]
Tweaking the messages shown with `dsl_load()`.
