### ISSUE TITLE
`dsl_get()`: stages and steps are missing

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#165]
Maybe because they are only run conditionally?

If `dsl_get()` outputs stages for me (see #164), then only the "install" and "script" stages are returned even though there are more stages and steps defined in `tic.R`.

(I currently can't even do a reprex because `dsl_get()` returns nothing constantly for me).

**Comment by krlmlr** [comment]
Your observation looks right to me -- it's most likely because some steps are added conditionally. Can we somehow give a nice example in the documentation? (If we build the documentation on Travis, we'll have `ci_is_travis()` and the `id_rsa` environment variable...)

**Comment by pat-s** [comment]
- `ci_is_travis()`-> `ci_on_travis()` now

- Even with `ci_can_push()` TRUE and forcing `ci_on_travis()` being TRUE, I am missing the deploy stages.

I tried a force init of the dsl storage with `dsl_load(force = TRUE)` but that did not help. 

Locally we are in class `MockCI` - is there some `memoise` caching going on that I am overlooking?

Should we print message in `dsl_get()` telling the user why certain steps are missing locally? This could happen by automatic detection of `MockCI`.
I guess users might expect all stages/steps by default and are not always aware that some are only run on a CI.

I know that all of this requires again some hours of work probably. But we should at least robustify the `dsl_get()` behavior locally.

**Comment by krlmlr** [comment]
`MockCI` is active with `load_all()`, when loading an installed package `LocalCI` is active.

We describe this effect in the "Advanced" vignette, let's keep it at that for now.
