### ISSUE TITLE
R CMD CHECK NOTE on large version components

### ISSUE THREAD

**Issue by lorenzwalthert** [ropenscilabs/tic#168]
testing on appveyor, I get the following note
```
Version contains large components (1.1.1.9000)
```

using `tic::do_package_checks()`. I don't get this note on travis. Here is an example commit: 

* [appveyor](https://ci.appveyor.com/project/lorenzwalthert/styler-bp2vm/builds/24436107)
* [travis](https://travis-ci.org/lorenzwalthert/styler)

It potentially is related to the discussion in https://github.com/r-lib/devtools/issues/1767 and https://github.com/r-lib/devtools/issues/1271, i.e. I suspect these env variables are not set the same in both ci services.

**Comment by pat-s** [comment]
We are just calling [rcmdcheck](https://github.com/r-lib/rcmdcheck) internally. So all strange check behavior is better reported there.

**Comment by krlmlr** [comment]
I'm not sure what's happening here, perhaps `r.rb` defines an environment variable. Should be fixed here, please comment if not.
