### ISSUE TITLE
Re-add support for deploying pkgdown to other branches than master

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#170]
I think this is currently not (easily) possible anymore.

With the current default, deployment is done to the `gh-pages` branch (which is ok as a default).

When `branch` is set to anything else besides `NULL` (e.g. `branch = ci_get_branch()`), then `deploy` is set to `FALSE` if `ci_get_branch()` does not evaluate to `"master"`.

https://github.com/ropenscilabs/tic/blob/72ff44bc21d01082810657955cdd54618ce1bb89/R/macro-pkgdown.R#L46-L59

Deployment can still be forced by using `do_pkgdown(deploy = TRUE, branch = ci_get_branch())` (which essentially just skips the whole if condition) but this is not very intuitive. And even then we should document `ci_get_branch()` better in this scenario.

Another way would be to use `do_pkgdown(branch = "master")` but here deployment would only happen if we are running on the master branch. 

#### Possible solutions

1. `do_pkgdown(branch = ci_get_branch())` should work in the first place, which would require an update of the second if-condition from the code-block above
2. `do_pkgdown(branch = "all")` and then call `ci_get_branch()` in the background for user convenience (requires 1.)

#### Refs

See [this build](https://travis-ci.org/mlr-org/mlr/jobs/534809846) for an example of a non-working deployment when using `do_pkgdown(branch = ci_get_branch())`

**Comment by krlmlr** [comment]
Does the `if` condition in line 56 match the documentation (=preceding text)?

**Comment by pat-s** [comment]
If `branch = NULL`, this happens: https://travis-ci.org/mlr-org/mlr/jobs/534731611

```
Original error: Must specify branch name if `path` is given.
```

In this case we skip the if block on l.56 and I was expecting a deployment to the current branch. (Sorry, I initially forgot to include the `branch = NULL` case.)

# 
Ah, `path = "docs"` by default and for deployment to the current branch we need `path = "."`.
Hm. Took me quite some time to figure this out.

Should document this setting directly in the details of `do_pkgdown()` to make it easier for users? Usually this is the alternative if one does not want to deploy to `gh-pages`.
