### ISSUE TITLE
do_pkgdown(): [ENOENT] Failed to search directory '*docs':

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#173]
This error came up in 3 repos now: https://travis-ci.org/r-spatial/mapview/jobs/538875309

Changing to `do_pkgdown()` solves the issue for _sf_  but not for _mapview_.
Could it be related to the branch checking within _do_pkgdown()_?

Maybe it is also random Travis behavior?

cross-ref: https://github.com/r-spatial/mapview/pull/203

**Comment by mitchelloharawild** [comment]
I've also been experiencing this issue: https://travis-ci.org/tidyverts/fable/builds/539055679#L1887
I noticed that you wanted to see if the behaviour persists, the issue first appeared for me a week ago in this check: https://travis-ci.org/tidyverts/fable/builds/536544731

**Comment by krlmlr** [comment]
Thanks for reporting!
