### ISSUE TITLE
README.Rmd generated figures don't show up

### ISSUE THREAD

**Issue by edzer** [ropenscilabs/tic#175]
In the [stars](https://github.com/r-spatial/stars) I moved to a dynamically created README.md, from README.Rmd. If the .Rmd generates figures, these figures do show up on the github repo site, but not on the opening site of the auto-generated [pkgdown site](https://r-spatial.github.io/stars/). It looks like the included and generated figures are not committed to the gh-pages branch. Is this a tic issue or do I overlook something?

**Comment by edzer** [comment]
Maybe related to #65?

**Comment by pat-s** [comment]
@edzer I just did a test deploy and for me the images show up: https://pat-s.github.io/stars/

[Build](https://travis-ci.org/pat-s/stars/jobs/589545423)

[Source](https://github.com/pat-s/stars/blob/c7e63282ffe5236ec714145988c1682c1338f2e9/README.Rmd)

Maybe a regression upstream in pkgdown that was fixed meanwhile?
I would just give it a try again.

Sorry for the delayed response.
