### ISSUE TITLE
Update required packages in `$prepare` step

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#184]
We ran into an issue in _mlr3learners_ in which _pkgdown_ was not updated for a long time and was producing unexpected outcomes.
_pkgdown_ gets installed by `$prepare()` within the `do_pkgdown()` macro.
However, it does not get updated automatically if there is no new cache for some time. Sometimes there is no cash refreshment until the next R version has been released.

Clearing the cache which includes a fresh installation solved the issue.
Currently, we are only checking if a required pkg is installed in `verify_install()` in the `$prepare()` step, we do not update the required packages.

**Comment by krlmlr** [comment]
I agree we should update all packages in the "prepare" step by default.
