### ISSUE TITLE
Use tic only for appveyor or circle CI ?

### ISSUE THREAD

**Issue by cderv** [ropenscilabs/tic#187]
I open this issue as question. 

I understand from the document that tic is compatible with circle ci and appveyor too, but it seems everything passes by `use_tic` and it will also configure travis and all. I see tic as independant of CI tools, and it is what I understand from here https://ropenscilabs.github.io/tic/articles/features.html

But... 

* Can tic be used without travis setting up ? `use_tic` won't let me get the circle ci template without installing travis package. 
* Is `use_tic` useful only for travis configuration ? From the source code, it seems it will always configure travis
* How should I setup for appveyor or circle ci ? No `use_circle_ci` or `use_appveyor` functions are exported to get the included template.  

I conclude that I can use tic, but I have to manually set it up for circle ci, looking at template in package and trying to reproduce. Am I right ?

**Comment by pat-s** [comment]
Hi,

we just merged initial support for circle a few days ago. 

`use_tic()` can certainly become smarter and its on our list :)

> Can tic be used without travis setting up ? use_tic won't let me get the circle ci template without installing travis package.

Currently we still require the _travis_ pkg in `use_tic()` as there was no alternative before for deployment. With the new circle ci option we will make that optional.

> Is use_tic useful only for travis configuration ? From the source code, it seems it will always configure travis

Right now it will always configure travis as this is how we started. Again, please have some patience :)

> How should I setup for appveyor or circle ci ? No use_circle_ci or use_appveyor functions are exported to get the included template.

In `use_tic()` you will be asked if you want to add support for appeyor. Have you gone through this?

> I conclude that I can use tic, but I have to manually set it up for circle ci, looking at template in package and trying to reproduce. Am I right ?

`use_tic()` should also set up circle if you proceed - if not please open an issue :)

**Comment by pat-s** [comment]
@cderv You might want to have a look at #193. There, one can use the `use_*_yml()` functions standalone. Also, `use_tic()` has been refactored from scratch and acts way smarter now.

**Comment by cderv** [comment]
Nice! I'll try that soon. Thanks for the head up!

**Comment by pat-s** [comment]
Done in #193.
