### ISSUE TITLE
New use_tic()

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#196]
- Check if specific packages are installed, don't offer option (with message) if not. Fail early.
- Show URLs visited, e.g. https://circleci.com/account/api, so that user can retry
- Memoize settings entered in GUI, offer to reuse when restarted and show how to forget, e.g. `use_tic(forget = TRUE)`
- `matrix` deprecated on Travis?
- {circle} didn't work on my system

**Comment by krlmlr** [comment]
@pat-s: Can we currently use Travis on both Linux and Mac with `use_tic()`?

**Comment by pat-s** [comment]
> Can we currently use Travis on both Linux and Mac with use_tic()?

Separately but not combined. `use_tic()` will overwrite the "macOS" selection with the later selected Linux selection (just tried it) and just use the latter.

It should be possible to select Travis for both macOS and Linux combined, yes.

**Comment by krlmlr** [comment]
I'm currently working on non-interactive `use_tic()`, PR coming very soon.
