### ISSUE TITLE
`use_tic()`: Ensure that a DESCRIPTION file is present

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#200]
Otherwise, macro functions will error during the CI run. See https://github.com/ropensci/software-review/issues/305#issuecomment-565823673.

- [ ] Assert a DESCRIPTION file in `use_tic()`. Create one if missing? Repo names with `-` are problematic.

- [ ] Mention (more clearly) that build dependencies are installed from packages listed in the DESCRIPTION file

**Comment by krlmlr** [comment]
Not sure we should require a `DESCRIPTION` for all projects.

**Comment by pat-s** [comment]
How should `step_install_deps()` work otherwise?

**Comment by krlmlr** [comment]
`step_install_deps()` raises an error if `DESCRIPTION` is missing, but the other steps don't.

**Comment by pat-s** [comment]
Hm ok, I was just thinking that this step is basically within every pipeline and therefore we could quite early if DESC is missing (instead of waiting until the CI build arrives there and errors).
But there are just too many ways that one can get started with {tic} - we cannot safeguard all of them.

One could also argue why one would use {tic} without a proper pkg/project infrastructure.

I am with you that this is a very debatable change that also comes with some hurdles regarding the checking of this (which is imo also out of {tic}'s scope).
