### ISSUE TITLE
Ensure that language: r is before os in .travis.yml

### ISSUE THREAD

**Issue by Robinlovelace** [ropenscilabs/tic#201]
Currently `use_tic()` can put this line at the top:

```
 # tic documentation: https://docs.ropensci.org/tic/dev/ 
```

This caused my build to fail I think: https://travis-ci.org/zonebuilders/zonebuilder/builds/628166249

**Comment by pat-s** [comment]
Thanks for reporting. It does not need to be the first line.
Maybe it needs to come before "dist" or "os"?

**Comment by Robinlovelace** [comment]
Maybe, yes that makes sense. Point is: `tic` generated a `.travis.yml` that failed with an unclear error message (I had to google it). BTW I tried `tic` but have reverted to just using instructions in `pkgdown` for Travis, after it refused to build (not sure why). 

Website is *finally* building: https://zonebuilders.github.io/zonebuilder/

**Comment by pat-s** [comment]
It was caused by the leading hyphens before the `#`:

```
--- # meta ---------------------------------------------------------------------
```

These slipped unintended.

Thanks for reporting!
