### ISSUE TITLE
About the Umlaut escape in DESCRIPTION

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#207]
@krlmlr Is this needed for CRAN or anything blocking? Just wondering because it breaks my pre-commit hook which always changes this back to "ü".

**Comment by krlmlr** [comment]
I remember switching to this notation due to some obscure problem on Windows (perhaps with `devtools::check_win_devel()`?). The umlaut seems to work well enough for most use cases, we can change it here if you prefer.

**Comment by pat-s** [comment]
> The umlaut seems to work well enough for most use cases, we can change it here if you prefer.

Thanks. That would be great.

I use `usethis::use_tidy_description()` frequently also standalone. However the hook thing is even more problematic. 

If `usethis::use_tidy_description()` changes it back to `ü`, can it really be an issue for CRAN/win-builder?

If so, it should be accounted for in {usethis}?
