### ISSUE TITLE
Issue when force deploy to master

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#30]
Hi there,

I am trying to deploy my `pkgdown` docs from the `dev` branch to `master/docs` but I keep facing conflicts with untracked git files introduced during travis building:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	sperrorest.Rcheck/
	sperrorest_2.1.1.tar.gz
	travis_wait_162.log
nothing added to commit but untracked files present (use "git add" to track)
Dropped refs/stash@{0} (26e5d8e7bad31ed5c4798cb77225478885791803)
Script failed with status 1
failed to deploy

```
https://travis-ci.org/pat-s/sperrorest/jobs/311851002

Any idea what I should do here?

**Comment by krlmlr** [comment]
I don't think the untracked files are the problem here: https://travis-ci.org/pat-s/sperrorest/jobs/311851002#L2107

I have never tested pushing, let alone force-pushing, to a different branch. You may be better off using gh-pages.

**Comment by pat-s** [comment]
I do so since a few days and pushing to `gh-pages` works smoothly!
