### ISSUE TITLE
[pkgdown] Some modified files are not deployed 

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#31]
Hi there,

in my last build I saw that some modified files by `build_site()` (e.g. `docs/index.html`) are not deployed to `docs/`. 

Travis build: https://travis-ci.org/pat-s/mlr/builds/311728468
Repo docs folder: https://github.com/pat-s/mlr/tree/master/docs

You can see that Travis build 42 pushed some files to `docs` but `docs/index.html` was not pushed by Travis build 42 although it was listed as modified in the Travis build (see link above). 
This caused that the hosted site still reflects the status before the deployment as the changes in `docs/index.html` are missing. 

Any idea why this is happening? :thinking:

**Comment by pat-s** [comment]
FYI: When deploying to `gh-pages` everything gets pushed which then triggers a correct site view. Probably due to `orphan = true` and the force push?

**Comment by krlmlr** [comment]
I recently fixed deployment issues, this may have affected deploy to master, too. Can you please retry?

**Comment by pat-s** [comment]
I've changed all my deployment to `gh-pages` recently since this methods was more robust to me due to the deployment of all files of the respective travis run.

In your [example package](https://github.com/krlmlr/tic.package/tree/master/docs) there are still single deployed files. Maybe its worth doing an force deploy to `master/docs` similar as to `gh-pages`?
 
In my case `index.html` was always missing and only some `.Rmd` files that changed were deployed. 
If `index.html` is now deployed every time, than the issue may be solved :) For now it works for me staying with `gh-pages`.

Anyhow, thanks for the great work and the simplified deployment! :+1:

**Comment by krlmlr** [comment]
Thanks. We can't force-push to master/docs, because that would obliterate the history in master. Need to review deployment to master. What do you mean by "single deployed files" in tic.package?

**Comment by pat-s** [comment]
> What do you mean by "single deployed files" in tic.package?

In my understanding it would be best if all files created by `pkgdown` in a build would be pushed together instead of only "single" modified ones. This leads to broken internal links in my experience (e.g. in `index.html`) and therefore I prefer to use the`gh-pages` approach which force pushed all files of the current build.

**Comment by krlmlr** [comment]
Thanks. Of course we should push all updates in a single commit, not doing this is a bug.
