### ISSUE TITLE
Pass on information between steps

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#38]
Example: A `"deploy"` step requires a path created in a `"build"` step.

Idea: Maintain a persistent cache of results, support naming steps. Fail with duplicate names.

**Comment by krlmlr** [comment]
- use rappdirs to figure out persistent location
- use build ID to determine file name
- use plain old `.Rdata` objects as container
- add new step `tic_store()` to store arbitrary objects
- add two new accessors: `tic_load()` to get results stored previously, `tic_last_result()` to get the results of the previous step

**Comment by krlmlr** [comment]
I think the effort to implement this in a robust way outweighs the benefits.

**Comment by pat-s** [comment]
I also do not really see large benefits in all of this compared to the work which would be needed to get this going.

Also we would need to document this in a very detailed way and not many people would have a use case for it.

Let's close this for now.
