### ISSUE TITLE
Support sequences of steps

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#40]
```r
get_stage("deploy") %>%
  sequence_start("pkgdown") %>%
  step_build_pkgdown() %>%
  step_push_deploy() %>%
  sequence_stop("pkgdown")
```

Need a better name for it.

**Comment by maelle** [comment]
A recipe?

**Comment by krlmlr** [comment]
This solves the problem of supporting early vs. deferred failure: currently, all steps of a stage are run even if some steps fail, but this doesn't make sense in deployment scenarios. Switching to early failure everywhere is much easier and more consistent with user's expectation.

We can then think of supporting the opposite: defining a "keep going" switch that enables deferred failure:

```r
get_stage("script") %>%
  set_keep_going() %>%

  # Run R CMD check
  step_rcmdcheck() %>%

  # lint the R source code
  step_lint() %>%

  # lint the documentation web page
  step_weblint()
```

**Comment by krlmlr** [comment]
Closing in favor of #59 and #60.
