### ISSUE TITLE
Feature request: travis_wait  option

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#41]
Would it be easy to add this option?

Naively I would assume to just add it as a prefix here

https://github.com/ropenscilabs/tic/blob/24d0820835f94028c934de36b28e6fa5670c3b53/R/steps-rcmdcheck.R#L52

using a if-condition triggered by an argument `travis_wait = FALSE`. 
The default should be quite high (> 100) to work for everybody. Or optionally definable by the user.

**Comment by pat-s** [comment]
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

**Comment by krlmlr** [comment]
`travis_wait` needs to be used in `.travis.yml`. But maybe we could persuade *rcmdcheck* to output progress to the console occasionally?

**Comment by pat-s** [comment]
Ah okay, I thought in the end it would be invoked to Travis in any case, no matter if using `tic` or not. 

Yes, sure - in the end there needs just a continuous output that can be optionally added. 

This is an approach that works, maybe you can somehow use it:

```bash
# add progress to ensure Travis doesn't complain about no output
while true; do
  sleep 30
  if jobs -rp | grep ${PID} >/dev/null; then
     echo "."
  else
     echo
     break
fi
done
```

**Comment by krlmlr** [comment]
We usually don't go back to the shell from *tic*, continuous output needs to be provided by the *rcmdcheck* package.

**Comment by pat-s** [comment]
@gaborcsardi Would it be possible to implement this in rcmdcheck?

**Comment by gaborcsardi** [comment]
What would it output?

**Comment by gaborcsardi** [comment]
But yeah, maybe one workaround is to start a process that runs in the background, and every five minutes outputs a dot? You can start it from `.travis.yml` I guess.

**Comment by pat-s** [comment]
Yes, a dot would be sufficient. Its only important that travis gets some output :+1:

**Comment by pat-s** [comment]
> Travis advises against wrapping all checks in a process that produces continuous output, because this makes it more difficult to detect actual hangs.

This means we should not use the "dot" approach?

**Comment by krlmlr** [comment]
We need a spinner or dots in processes where we know that they might run longer, and that running a bit longer is not an error. We can couple this with the `timeout` argument in `rcmdcheck::rcmdcheck()`.

It just feels bad to unconditionally print dots for all steps.

**Comment by pat-s** [comment]
The problem is that `travis_wait` by default does not allow progress output, that's why people prefer the "dot" approach.

**Comment by pat-s** [comment]
@gaborcsardi should I file an issue at `rcmdcheck`? How are your thoughts about implementing this?

**Comment by gaborcsardi** [comment]
I am reluctant to implement this in rcmdcheck, it does not seem to belong there. Can't  you just start a background process that puts out dots?

**Comment by gaborcsardi** [comment]
Maybe. I don't know what Travis does with background processes, so why don't you just give it a try?

**Comment by pat-s** [comment]
I will. Just thought you may have already tried it during one of your projects. I'll report back :)

**Comment by pat-s** [comment]
Got it working by reducing the time of each sub-test so that Travis does not timeout.
