### ISSUE TITLE
Feature request: Deploy single files

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#42]
Currently, one can only deploy directories using `step_push_deploy()`, is that correct?

It would be great if the `path` argument could detect if the path given is a directory or a file and do the right thing.

Also, currently a push seems to wipe the complete repo?
While this is fine for a clean `gh-pages` branch or `docs/` folder, it does not help for single file deployments. 
I looked into the source code but adapting such a function seems to be harder than initially thought (no experience yet with R6).

**Comment by krlmlr** [comment]
Git deploys always affect the entire repo, but we should be able to add only selected files.

The default `orphan = FALSE` isn't supposed to wipe the repo, would you like to share your use case or configuration?

**Comment by pat-s** [comment]
[tic.R](https://github.com/pat-s/mlr/blob/master/tic.R)

The "PDF" section has `orphan = FALSE` and wiped my repo.
I just reverted with a force push so the commit is not visible anymore.

Basically, I just want to deploy a single PDF file after creation. You can see the steps in the travis.yml and tic.R files.

**Comment by krlmlr** [comment]
The path is the new root of the repository, this works as expected. For now you'll need to update the entire repo, but I'm happy to support an argument that restricts the files to be added for the deployment.

**Comment by pat-s** [comment]
That would be great! Adding single files without overwriting the complete repo :+1:

**Comment by krlmlr** [comment]
Can you please try `step_push_deploy(subdir = "...")` ?

**Comment by pat-s** [comment]
Reading the doc, `subdir` will only accept dir paths and will add the complete directory to git and then again wipe the specified branch?

What is the difference to the `path` argument? I currently use a subdir path with `path`.

**Comment by krlmlr** [comment]
Yes, `subdir` is a bit of a misnomer. Maybe we can find better names?

`path` is the root of the Git repo. `subdir` is a (vector of) local path(s) in that repo.

**Comment by pat-s** [comment]
But `subdir` always needs to be a dir or can it also point to a single file?

**Comment by krlmlr** [comment]
Single file(s) will work too, but the documentation currently isn't explicit about it. Happy to take suggestions for better argument name and/or documentation.

**Comment by pat-s** [comment]
Ok thats cool! Trying it out now.

When single files are also fine, `subdir` is definitely misleading. What about something like `files_to_commit`? Looks more descriptive to me in that context. And then simply mention in the arg doc that it can be either a dir or a vector of files?

**Comment by krlmlr** [comment]
Done, it's called `commit_paths` now: caeaddc.

**Comment by pat-s** [comment]
Sounds good!

**Comment by pat-s** [comment]
@krlmlr any idea why in [this build](https://travis-ci.org/mlr-org/mlr/jobs/362305251) also `tic.R` got deployed? https://github.com/mlr-org/mlr/commit/699081ab3e8d5ff7fcec90d28e1d8305d18c86b3

The change in `tic.R` was the commit that triggered the build in the first place. But it should not be deployed then as its not within `commit_paths`?

**Comment by krlmlr** [comment]
Perhaps because the branch `travis_test_deploy` wasn't updated? For updates to the same branch pleas omit the `branch` argument.

**Comment by pat-s** [comment]
You mean `commit_paths`?

This was set as you can see in the linked `tic.R`.

**Comment by krlmlr** [comment]
I think `step_push_deploy(branch = "xxx")` can't work reliably without also specifying a `subdir` argument; the subdir is supposed to be `.gitignore`-d in the main branch, too. Example:

```r
step_push_deploy(branch = "gh-pages", subdir = "docs")
```
