### ISSUE TITLE
Build passes with errors in rcmdcheck

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#44]
See this build log: https://travis-ci.org/mlr-org/mlr/jobs/370482092

Not sure if this is a `tic` or `rcmdcheck` issue. 

Repo: https://github.com/mlr-org/mlr

**Comment by krlmlr** [comment]
I'm only seeing a `NOTE`, you need to say `step_rcmdcheck(notes_are_errors = TRUE)`.

**Comment by pat-s** [comment]
In the summary yes, but look at line 2030. Errors in the tests and yet the summary shows no errors? Probably a `rcmdcheck` issue then after thinking about it again. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by krlmlr** [comment]
Thanks!

**Comment by pat-s** [comment]
This also happens when using `R CMD Build` instead of `rcmdcheck()`: https://travis-ci.org/mlr-org/mlr/jobs/395790335

Hence, I assume its unrelated to `rcmdcheck()` and a issue of `tic`.

**Comment by krlmlr** [comment]
I'm confused. The code you pointed to is only active if your `tic.R` contains `add_step(step_rcmdcheck(...))` or `add_package_checks()`.

Moreover, a `system()` or `system2()` call will return the exit code, which is zero for successful processes. To make _tic_ stop on error, you need `stopifnot(system(...) == 0)` or similar. I don't remember if `R CMD check` sets the status code, maybe you need to check the log output.

I think we should try to make it work with _rcmdcheck_. I'll take a look.

**Comment by pat-s** [comment]
> I'm confused. The code you pointed to is only active if your tic.R contains add_step(step_rcmdcheck(...)) or add_package_checks().

Yeah forget about that, I saw it after commenting.

> I think we should try to make it work with rcmdcheck. I'll take a look.

Yes that's most important. As Gabor pointed out, we could first find a way how to extract `x = rcmdcheck()` as an artifact without too much hassle.

**Comment by pat-s** [comment]
I am right now trying to upload `x = rcmdcheck()` to S3 automatically in [this branch](https://github.com/mlr-org/mlr/tree/tic-debug-s3) using my fork of `tic`. 
If that works out, we/Gabor can inspect the problem in more detail.

**Comment by krlmlr** [comment]
Thanks a lot for your help! You could also use the debugging feature of Travis CI. This needs to be enabled for the repo, but then you can use `travis::travis_debug_job()` to start a job where you can SSH into.

**Comment by pat-s** [comment]
Oh thats nuts! Will ask for permission and see what I can find. Thanks!

**Comment by pat-s** [comment]
Solved by an update of `rcmdcheck`.
