### ISSUE TITLE
Push step may undo changes in master 

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#45]
See r-dbi/DBI@d5290c0e78a and its parent.

**Comment by pat-s** [comment]
We also faced this in `mlr`: https://github.com/mlr-org/mlr/commit/12864caf6438918f80070d10c44e629666970a99

**Comment by krlmlr** [comment]
Thanks. It's strange that other files were deployed besides `NEWS`. The safest thing would be to operate on `FETCH_HEAD`, commit there, and then try to deploy that to `master`. If this fails then probably another commit got in the way, and we fail the deploy (maybe push to a new branch beforehand). I'll take care of checking this in #62.

**Comment by krlmlr** [comment]
Tricky problem here.

Suppose `master` has commits `A`, `B`, `C`, CI runs for commit `A`. The deployment is run against commit `A`, but we need to add our commit on top of commit `C` (otherwise we can't push).

`A--B--C` then becomes `A--B--C--A'` .

The issue described here arises because the code incorrectly issues `git reset C` when `A` is checked out. This doesn't change the file system contents for the clone, and has the effect that `A'` reverts `C` and `B`.

What are the alternatives?

- Do not reset, commit `A'` on top of `A`. What then? One of:
    1. Fail when pushing
    2. Run `git pull --rebase`
    3. Push to a separate branch, issue a pull request
    4. Create and push a synthetic commit `X` to trigger another CI run
    5. Do nothing
- When deploying, always use the latest tip. This doesn't guarantee that deployment uses tested code
- Rebase to `A--A'--B--C`, then force-push -- very risky
    - What if `C` has `[ci skip]`, will a CI run be started for `B`?
    - What if CI for `B` is already running? What if CI for `B` has completed before?
- ?

**Comment by krlmlr** [comment]
Maybe a feasible strategy:

- Commit `A'` on top of `A` in a branch
- Reset to `C`
- Cherry-pick `A'` onto `C`
    - Failure: fail deploy
    - Success: go on

**Comment by pat-s** [comment]
Great that you figured out the problem already!

Not sure if it helps, but the git commands we used in `mlr` never triggered such problems. 

Maybe you can get inspired by them to solve this problem here. 
Looks very basic but does a robust job in practice.
https://github.com/mlr-org/mlr/blob/deaad6496df63de10b8d1af0b3f6b6663dea3fd5/.travis.yml#L52-L67

        - git checkout master
        - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
        - R --no-save <<< "devtools::document(roclets=c('rd', 'collate', 'namespace'))"
        - ./thirdparty/gen_families.sh > man/mlrFamilies.Rd
        - git config user.name $GN
        - git config user.email $GM
        - git config credential.helper "store --file=.git/credentials"
        - bash inst/convert_to_ascii_news.sh
        - echo "https://$GT:@github.com" >> .git/credentials
        - git config push.default matching
        - git add --force NEWS
        - git add --force man/*
        - git add --force NAMESPACE
        - git commit man DESCRIPTION NAMESPACE NEWS -m "update auto-generated documentation [ci skip]" || true
        - git push
        - "[ $TRAVIS_PULL_REQUEST == \"false\" -a $TRAVIS_BRANCH == \"master\" ] && curl -s -X POST -H \"Content-Type:application/json\" -H \"Accept:application/json\" -H \"Travis-API-Version:3\" -H \"Authorization:token $TT\" -d \"{\\\"request\\\":{\\\"branch\\\":\\\"gh-pages\\\", \\\"message\\\":\\\"commit $TRAVIS_COMMIT $TRAVIS_COMMIT_MSG\\\"}}\" https://api.travis-ci.org/repo/mlr-org%2Fmlr-tutorial/requests"

**Comment by krlmlr** [comment]
Thanks. This does look interesting but how are race conditions dealt with in your script? It looks like the `git push` will just fail -- not ideal.

Cherry-picking seems to work.

**Comment by pat-s** [comment]
> It looks like the git push will just fail -- not ideal.

Probably. Not ideal but safe - and since we only use it for automatic man/ deployment, this will just be done in the last commit that isn't in a race.
But if you deploy other files its not perfect, sure.

> Cherry-picking seems to work.

If that works, great :+1:

**Comment by krlmlr** [comment]
Implemented in e136aa2b13e1d9ae57b8a0f8910dbf2d770ec284.
