### ISSUE TITLE
Stages and steps need clarification for the end user

### ISSUE THREAD

**Issue by karthik** [ropenscilabs/tic#47]
>  tic embraces this concept. Each stage has a name (e.g., "after_success", "deploy", ...) and has an arbitrary number of steps. 

The documentation needs to address how a user makes sense of `after_success` and say `deploy`. e.g. if a user were to use this to build package docs with pkgdown, then on success, they would include the recipe to "deploy" the docs to a branch. Then where does deploy come into play since we just deployed under `after_success`. This type of ambiguity needs clarification since we cannot assume the end user understands these stages.

**Comment by krlmlr** [comment]
- function that emulates a Travis/Appveyor run
- reduce steps to lcd between Travis/Appveyor
- flow chart?

deploy: failure aborts build
aftersuccess: failure does nothing

**Comment by maelle** [comment]
A flow chart would be really useful (for this but also in general actually, so probably several flowcharts?).

**Comment by maelle** [comment]
When I say in general I mean the general concept of using GitHub and Travis CI to deploy "stuff".

**Comment by krlmlr** [comment]
We could point users new to Travis CI to e.g. http://mahugh.com/2016/09/02/travis-ci-for-test-automation/.

The "build lifecycle" is described at https://docs.travis-ci.com/user/customizing-the-build#The-Build-Lifecycle, but they don't have a flow chart and the description isn't particularly detailed (e.g. it doesn't explain that failures in `after_install` etc. don't trigger a failed build). I couldn't find anything similar for AppVeyor. Maybe upstream needs better documentation too.

I have created https://github.com/krlmlr/ci-lifecycle to test various failure modes in the Travis CI and AppVeyor lifecycles, this repo could also host a more detailed description and the flow charts.

**Comment by krlmlr** [comment]
Build in the ci-lifecycle repo: https://travis-ci.org/krlmlr/ci-lifecycle/builds/397482622

![screenshot from 2018-06-27 20-54-25](https://user-images.githubusercontent.com/1741643/41993613-4ca0b85e-7a4c-11e8-9a2b-1b740a3ee2a6.png)

**Comment by krlmlr** [comment]
Closing in favor of #57, which contains the structure of a new vignette to be written. Happy to continue discussion there.

**Comment by krlmlr** [comment]
#57 incorporates most of the topics discussed here, some are solved already.
