### ISSUE TITLE
Custom steps

### ISSUE THREAD

**Issue by karthik** [ropenscilabs/tic#50]
This part of the README could use a figure of some sort to help the under understand the workflow.

**Comment by krlmlr** [comment]
No user will use custom steps if they can achieve the same with a code step. This belongs in an "implementation" vignette.

**Comment by krlmlr** [comment]
The vignette still needs more details and a worked example.

**Comment by krlmlr** [comment]
I think we're good here: https://ropenscilabs.github.io/tic/articles/custom-steps.html. Please comment/open a new issue if this needs more work.
