### ISSUE TITLE
My dummy perspective

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/tic#55]
:wave: @krlmlr 

This package is fantastic, so useful!

When I started using `tic` for https://github.com/ropenscilabs/dev_guide I looked at the README and saw the example applications and copy-pasted stuff from the example bookdown repo. I also checked whether there was a vignette, but I didn't read the documentation of each function because I'm too lazy I guess? And because I figured everything was figured out in the example repo. 🙈 Then when I realized an RSA key was needed, I tried figuring out on my own because I hadn't thought of `travis` (that I see is mentioned in the docs of this package, so my fault).

Here are my suggestions for the docs:

* Near the example applications have a link to a vignette explaining setup for these examples, including reminding this package is better used in combination with `travis`.

* Maybe have some higher-level functions for the example applications, i.e. could I run a single function in a bookdown repo and have the whole setup done with the default options (like what I did by copy-pasting tic.R and the .sh files) I think that's your idea in #40 

* Not really doc but in https://github.com/krlmlr/tic.bookdown/blob/70e54d1afc3f46a0f619edd592a9804834a0445d/tic.R#L13 if there's no id_rsa would it be possible to output a message about `travis::use_travis_deploy` that the user would see in Travis log?

**Comment by maelle** [comment]
* At the beginning of the README "The goal of tic is to faciliate deployment tasks for R" (typo btw) it'd be great to add more concrete examples. Maybe the reader doesn't know they need a deployment task so explain what problem it solves. Like being tired of triggering updates of docs derived from source code by hand etc.

**Comment by lorenzwalthert** [comment]
I agree with @maelle. I am a bit intimidated by `tic`, it seems like magic 😅. Some high-level instructions would definitively be helpful. I think one could also link repos that use `tic` so people can see practical use cases with source code.

**Comment by maelle** [comment]
By the way the existing example repos like [`https://github.com/krlmlr/tic.bookdown`] should link back to `tic` repo IMO. It might even make sense to transfer them to ropenscilabs, and to have a specific repo topic that other use cases could use, maybe "r-tic" or so.

**Comment by krlmlr** [comment]
Thanks for your input. I think the README needs a complete rewrite, and there should be a "Get started" vignette that describes how everything is linked. The fairly new `travis::use_tic()` function will do most of the setup, for now I'll add a reference to this function to the README.

**Comment by krlmlr** [comment]
The docs are in a much better shape now (thanks @pat-s!), do we need to take any action here?

**Comment by pat-s** [comment]
@maelle We are really close to start the ropensci review. Any suggestions beforehand from your side? Otherwise feel free to close here :)

**Comment by maelle** [comment]
Only small comments on the README

* In https://github.com/ropenscilabs/tic#examples it'd be helpful to know whether the examples work with Travis or Appveyor.

* In https://github.com/ropenscilabs/tic#vignettes I wouldn't start with "Advanced usage" :smile_cat: Actually that list isn't even up-to-date, the order is good on the pkgdown website.

**Comment by krlmlr** [comment]
Forgot to merge the documentation update, done now.

**Comment by krlmlr** [comment]
Thanks for your feedback! I didn't notice that you were referring to the README on GitHub -- should be better now.
