### ISSUE TITLE
"Get started" vignette

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#57]
Write from scratch, starting from a mental model of a user who knows what CI is.

See the pull request for a rough structure, feel free to edit.

The new README can be a condensed version of the "Getting started" vignette.

**Comment by krlmlr** [comment]
Maybe there's room for multiple vignettes describing each aspect in detail, and the "Get started" vignette contains a rough overview and pointers.?

**Comment by maelle** [comment]
Maybe start with motivations, i.e. challenge solved by the package?

By the way in https://ropensci.github.io/dev_guide/ci.html we link to https://juliasilge.com/blog/beginners-guide-to-travis/ maybe you'll want to do that (so that people who don't know CI yet can go read, learn, and come back 😉 )

**Comment by krlmlr** [comment]
I updated the structure, I'll move that to an `.Rmd` file in a PR very soon.

**Comment by krlmlr** [comment]
Done, happy to take your input there.

CC @lorenzwalthert.

**Comment by pat-s** [comment]
Working branch: https://github.com/pat-s/tic/blob/f-new-vignette/vignettes/tic.Rmd

**Comment by krlmlr** [comment]
I like the way the new vignettes are organized, they are good read.
The relevant information is presented concisely, with good cross-references.
Especially the automatic linking from code chunks to function documentation done by _pkgdown_ makes the vignettes easy to navigate.

The vignettes could use some graphics, screenshots, and code blocks/listings.
They could be a bit more self-contained, too -- e.g. show an example instead of a bare link pointing to additional information.
The examples are important to give the user an early understanding if following the link is worthwhile.

# README

- [ ] Link to CI intro (mahugh.com), brief before-after comparison (with image from ) and link to "advantages" website
- [ ] "Example projects" is anchored link, just mention when introducing the "Get started" vignette?
- [ ] Footer on website?


# Get started

- [ ] Prerequisites: Second paragraph lengthy and diluted; instead briefly summarize tic's advantages in a comprehensive bullet list (one item per benefit, like in the intro of the "Advantages" vignette), add a before-after like in README, and link to `tic-advantages.html`
- [ ] Initialization: Again, can be a bit longer, showing the call and the expected output in a full-width chunk. Mention that browser pages will open and app authorization is required, and a PAT needs to be created, add screenshots. Explain why this is necessary, especially that PAT creation can't be automated currently.
- Setup
    - [ ] Consider renaming section
    - [ ] Show and explain example `tic.R` file (copy template to the package for now, it might stay there for good, or we take the template from _usethis_ later)
    - [ ] Don't show example `.travis.yml` and `appveyor.yml` files, but point to the "Build lifecycle" article
- [ ] Examples
    - [ ] In the bullet list, add a brief explanation, e.g. for blogdown: what is blogdown, how is deployment achieved, is there anything special about the example repo, maybe show excerpts from `tic.R`?
    - [ ] The link names should match the repo names
    - [ ] figshare publishing doesn't work yet, publishing to Zenodo is work in progress (need to ask Karthik)
    - [ ] CTA: share your own nonstandard _tic_-based solutions?
- [ ] What's not covered yet: move to "Advanced"

# Advantages

- [ ] Title is repeated on rendered website?
- More advantages
    - [ ] Easier troubleshooting for local builds (with link); it's mentioned in "CI-Agnostic" but deserves its own section with a working example
    - [ ] Less dependent on code we don't control (e.g. `r.rb`)
- CI-agnostic:
    - [ ] `tic.R` is shorter and easier to parse than `.travis.yml`
    - [ ] AppVeyor is running on Linux since recently
- Easier deployment:
    - [ ] Formatting: Indent code blocks and subsequent paragraphs with four spaces to make them indented in the enumeration
    - [ ] Shorten, keep first paragraph and link to new "How deployment works" vignette
- R CMD check:
    - [ ] Section title unclear
    - [ ] _rcmdcheck_  calls into `R CMD build` and `R CMD check` (it's not reimplementing it), parses output and returns errors/warnings to the caller as an R object
    - [ ] Show excerpts of colored output (use `fansi::sgr_to_html()` to create HTML)
- Caching:
    - [ ] Link to "Build lifecycle"
    - [ ] Build deps and check deps are stored in two separate libraries, both are cached. Not sure how to frame it, let's discuss.

# tic, travis, and usethis

Pending decision on where setup code is hosted.

Overall, I think a detailed walkthrough (expanding on what will be shown in "Get started") can add some value here.

    
# Build lifecycle

- Stages:
    - [ ] Article title repeated?
    - [ ] Need diagram
    - [ ] Mention that `.travis.yml` is not meant to be edited (include the "DO NOT EDIT" comments in the code)
    - [ ] How does a stage is accessed from R code? Show an example `tic.R` file and the output of e.g. `get_stage("script")`
- Steps:
    - [ ] Mention macros (#61, to be implemented)
    - [ ] Add steps not mentioned there yet
    - [ ] Link steps to help pages, this should happen automatically if you add `()` after the step names
    - [ ] Add more detail to the documentation of the steps


# New vignette: How deployment works

Derived from "Easier deployment" in the "Advantages" vignette, and "pkgdown deployment" and "committing single files" in "Advanced usage".

- _tic_ creates public-private key pair
    - public key is added to GitHub repository under the "Deploy keys" section (screenshot), user receives e-mail
    - private key is encoded in base64 and stored in an environment variable, and installed in the `~/.ssh` directory during the CI run
- Prefer deployment via public-private key pair, because rights are granted to a single repo only and can be automated
    - We do create per-repo PATs anyway, but these have a very restrictive scope just to avoid rate limitation.
    - Need to revisit: perhaps creating a PAT with write permissions is easier if we can make sure that our scripts never leak the PAT?


# Advanced usage

- pkgdown and Committing single files:
    - [ ] Move to "How deployment works"
- Running stages conditionally:
    - [ ] Mention that `tic.R` is a file that is processed with `source()`
    - [ ] Steps are added incrementally, existing steps created by macros aren't overwritten
    - [ ] R version can be checked with `getRversion()`, show example where `warnings_are_errors` depends on the R version used (ignoring warnings for R 3.1)
- Installing packages:
    - [ ] `s/add_code_step/add_step/`
    - [ ] Mention that it shouldn't be used in interactive CI runs (`ci()$is_interactive()`)
    - [ ] Packages should be installed from `DESCRIPTION`, install manually only in extraordinary circumstances
- Meta:
    - [ ] Remove "Travis" from title
- Running tic locally:
    - [ ] Show example output for `load_from_file()`
    - [ ] Important: define steps so that they don't overwrite precious local state. Many steps are careful (double-check this), but custom code may be not
- Entering:
    - [ ] Elaborate on opt-in, mention that it needs an e-mail which will be acted upon in less than one day usually.
    - [ ] How to get the job ID? Show example in separate code chunk.
    - [ ] Link to `tmate` key bindings documentation, mention similarity with `screen` and overarching Ctrl + A shortcut (and two or three most important ones, e.g. for scrolling back)
    - [ ] Handy functions: Which ones?


# Dev info

- [ ] "Most steps" -> "Many important steps". Always possible to add a code step, this text is only important for reocurring use if we want to add a new step to _tic_.
- [ ] Point to PR that adds `step_install_cran()`
- [ ] Show source code of the "Hello world" step
- [ ] `check()` doesn't need to be overridden
- [ ] `prepare()` is called by `prepare_all_stages()`
- [ ] Show code of `RCMDcheck$prepare`
- [ ] Start subsection before "If you are unfamiliar"

**Comment by krlmlr** [comment]
Closing in favor of #78.
