### ISSUE TITLE
Macros for reoccurring workflows

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#61]
Like `add_package_checks()`, perhaps useful for deploying documentation via _pkgdown_ and other frequent tasks.

I suggest starting with explicit code in `tic.R` (via `add_code_step()`) and then try to identify reoccurring patterns, as opposed to implementing these in advance.

https://github.com/ropenscilabs/tic/issues/55#issue-331843792, second bullet point.

**Comment by krlmlr** [comment]
Use examples from unmerged PR 94.

**Comment by pat-s** [comment]
I guess we should provide macros for all workflows of the listed example repos?

**Comment by krlmlr** [comment]
Not sure. Maybe one more macro, I'm already fine with package checks and pkgdown.

**Comment by krlmlr** [comment]
Deploy a website, perhaps?

**Comment by pat-s** [comment]
> I guess we should provide macros for all workflows of the listed example repos?

In the long run, for CRAN pkg checks and pkgdown are sufficient for now.
