### ISSUE TITLE
Add pkg documentation macro

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/tic#65]
Is there already/could there be a `tic` example showing how to deploy README.md from Travis when there's a README.Rmd and how to use `roxygen2::document` similarly?

I'd use that in so many packages :joy:

**Comment by pat-s** [comment]
This could be achieved by

```r
get_stage("deploy") %>%
  add_code_step(rmarkdown::render_site()) %>%
  add_step(step_push_deploy(commit_paths = <path-to-README.md>, branch = "master, orphan = FALSE))
```
Do you mean `devtools::document()` instead of `roxygen2::document()`?
To deploy `man/` files?

Then this would be 

```r
get_stage("deploy") %>%
  add_code_step(rmarkdown::render_site()) %>%
  add_code_step(devtools::document()) %>%
  add_step(step_push_deploy(commit_paths = c("<path-to-README.md>", "man/*"), 
             branch = "master, orphan = FALSE))
```

Note that this approach is not really stable right now as sometimes the commited changes are reverted by the automatic deployment -> #45

**Comment by maelle** [comment]
Thanks a lot!

Will wait a bit then

**Comment by krlmlr** [comment]
Deploying to master should be stable now.

**Comment by maelle** [comment]
Btw the "deploying to master" parts of what one can do with `tic` won't be the default, right? I.e. by default `use_tic()` won't mean creating the docs on Travis?

**Comment by pat-s** [comment]
> Btw the "deploying to master" parts of what one can do with tic won't be the default, right? I.e. by default use_tic() won't mean creating the docs on Travis?

Not sure if I understand what you mean here. 
You can deploy from any CI as long as the keys are set for deployment.
This process is currently easiest on Travis. 

What do you mean "won't be the default"?

**Comment by maelle** [comment]
I mean that if setting up tic stuff for a package, by default it will include building the man pages.

**Comment by pat-s** [comment]
Ah no, that's not the default as not everyone would want this.
Lines 42-43 in https://github.com/mlr-org/mlr/blob/master/tic.R are an example how to do this 🙂 as mentioned, it should be stable now. We're using it mlr since months without problems.

**Comment by pat-s** [comment]
We could add a macro for deploying man/ and README.Rmd each? But maybe after the CRAN release. Until then the steps need to be inserted "manually".

**Comment by krlmlr** [comment]
We now have `do_pkgdown()`.

**Comment by pat-s** [comment]
I think this here was about automatic deployment of README.Rmd and calling `devtools::document()` to create and deploy man/ files?

**Comment by pat-s** [comment]
@maelle 

Wondering if we should add macro or if these three lines are self-explanatory enough?

```r
get_stage("deploy") %>%
  add_code_step(rmarkdown::render("README.Rmd")) %>%
  add_step(step_do_push_deploy(commit_paths = "README.md"))
```

**Comment by maelle** [comment]
I think so, although these days I think I would mostly document locally 🙈 thanks in any case!
