### ISSUE TITLE
New step_install()

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#69]
to simplify installation of CI-only dependencies like _magick_ for favicons in _pkgdown_.

**Comment by pat-s** [comment]
We could to the same for GH installations:

Instead of `add_code_step(remotes::install_github("r-lib/rcmdcheck"))` -> `step_install_github("r-lib/rcmdcheck"))`

Alternatively also for Gitlab.

**Comment by krlmlr** [comment]
For GitHub (and other) packages, _remotes_ checks if the package is installed, it's not as crucial to have it. Too bad there's no `remotes::install_cran()` (yet).

**Comment by krlmlr** [comment]
Closed by PR.
