### ISSUE TITLE
Add some protection against typos in tic.R

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#73]
On a build with an empty cache: https://travis-ci.org/pat-s/tic.package/builds/412160129

**Comment by krlmlr** [comment]
Seems to be related to a syntax glitch:

https://github.com/pat-s/tic.package/blob/5f6bbe51c2fb996530ea34ea511a2aa640341273/tic.R#L18

Suggestion:

- [ ] `add_step()` forces its argument in a `tryCatch()` and gives a legible error message if anything goes wrong
- [ ] `add_step()` checks the class or the elements of its argument (is it of class `TicStep`, does it have elements `"prepare"` and `"run"`, ...), and gives a legible error message if not
