### ISSUE TITLE
New function to print the tic workflow to the console

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#77]
- [ ] Return classed object in `load_from_file()`
- [ ] Implement `print()` methods for this classed object
- [ ] Rename `Stage` to `TicStage`, `DSL` to `TicDSL`
- [ ] Implement `print()` methods for `TicStage` and `TicStep`
- [ ] Adapt vignette(s)

Useful for vignettes, can also be used in a code step to show the workflow.

**Comment by pat-s** [comment]
Good idea!

**Comment by krlmlr** [comment]
Working on providing really pretty output using tidy evaluation.

**Comment by krlmlr** [comment]
Also need to print steps. Ideally, one could source a `tic.R` file.

**Comment by krlmlr** [comment]
Closed in 2af4c91.
