### ISSUE TITLE
vignette builder 'knitr' not found

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#84]
commit 5f1a22bae94be3df4817d7cc0bfdf2953021c93f removed

```r
get_stage("install") %>%
  add_code_step(remotes::install_deps(dependencies = TRUE))
```

from `add_package_checks()`.
Now when I run `tic()` locally (on the tic repo), I get

```r
tic()
Running script: step_rcmdcheck(warnings_are_errors = warnings_are_errors, notes_are_errors = notes_are_errors, args = args)
Error: 
Build failed, standard output:

* checking for file ‘tic/DESCRIPTION’ ... OK
* preparing ‘tic’:
* checking DESCRIPTION meta-information ... OK

Standard error:

Error in loadVignetteBuilder(pkgdir, TRUE) : 
  vignette builder 'knitr' not found
Execution halted
```

Even when I add the install_deps() again, I still see

```r
tic()

Running install: step_run_code(remotes::install_deps(dependencies = TRUE))
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo krlmlr/callr@b-55-vignette-builder
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo r-lib/processx@master
Installing package into ‘/home/pjs/R/x86_64-pc-linux-gnu-library/3.5’

[...]

Running script: step_rcmdcheck(warnings_are_errors = warnings_are_errors, notes_are_errors = notes_are_errors, args = args)
Error: 
Build failed, standard output:

* checking for file ‘tic/DESCRIPTION’ ... OK
* preparing ‘tic’:
* checking DESCRIPTION meta-information ... OK

Standard error:

Error in loadVignetteBuilder(pkgdir, TRUE) : 
  vignette builder 'knitr' not found
Execution halted
```

Some "interactive" problems?

**Comment by lorenzwalthert** [comment]
Reference: https://github.com/r-lib/styler/issues/46#issuecomment-389493313

**Comment by lorenzwalthert** [comment]
I managed to resolve this manually, but then it seems as other dependencies are missing as well: https://travis-ci.org/lorenzwalthert/styler/jobs/420072316
How can it be that they are missing at the `tic::script()` step?

**Comment by lorenzwalthert** [comment]
I recall I tried to manually add installation calls with `add_code_step()` and it also did not work.

**Comment by pat-s** [comment]
Since some commits we use a dedicated library only for R cmd check. This library seems to miss the `knitr` package.
However, then `knitr` would need to be installed into `/home/travis/R/library/tic-lib` to be recognized.
However, calling `add_step(step_install_cran("knitr"))` helps here even though I would expect `add_step(step_install_cran("knitr", lib = "/home/travis/R/Library/tic-lib"))`.

Seems we have some severe usage issues currently in `tic`. I am really struggling to get the guys convinced to stay with `tic` atm as its so unstable lately (I know we're maturing and are not on CRAN yet but reverting everything is a big thing that I would like to avoid). 

We need to figure out why `knitr` is not installed as a dep into `/home/travis/R/Library/tic-lib` (or is even `/home/travis/R/Library/` used here?). Also, if one installs `knitr`, the next missing pkg is `rmarkdown` -> https://travis-ci.org/pat-s/stars/jobs/422276883#L1914

**Comment by krlmlr** [comment]
I'm seeing similar problems in _DBI_. The other thing that changed is that we're now using `master` for _callr_, and not my bugfix branch.

I enabled Travis CI debugging for the _DBI_ repo, will take a look.

**Comment by lorenzwalthert** [comment]
Completely agree with @pat-s, this needs to be fixed asap. Do we have unit tests for these kinds of things?
>  Also, if one installs knitr, the next missing pkg is rmarkdown

Yes, I ad the same problem. I fixed it for styler for now just adding `install.packages("knitr", "rmarkdown"); remotes::install_deps(dependencies = TRUE)` to the `.travis` file, which is - I agree - not terribly elegant but apparently works for now. To be honest, Why not `git checkout [ref before problems]` and then iterate on a devel branch?

**Comment by pat-s** [comment]
It seems that the vignette checkings take `/home/travis/R/library` and not `/home/travis/R/library/tic-lib` since all deps are missing: https://travis-ci.org/pat-s/stars/jobs/422292081#L2859

**Comment by krlmlr** [comment]
Should work in the latest dev version of _tic_, sorry for the trouble. CC @edzer @tim-salabim.

**Comment by lorenzwalthert** [comment]
Thanks @krlmlr will try it out soon.

**Comment by lorenzwalthert** [comment]
Same problem again but only for R 3.1: https://travis-ci.org/r-lib/styler/jobs/520066212.

**Comment by pat-s** [comment]
AFAIK we dropped support for < 3.2 due to some major changes in the `knitr` package or one its friends which makes everything below R 3.2 quite complicated. Imo tests for R < 3.2 can be safely skipped - we are at 3.6 soon.

**Comment by lorenzwalthert** [comment]
Ok, thanks.
