### ISSUE TITLE
step_rcmdcheck does not find installed dependencies

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#87]
In this build: https://travis-ci.org/mlr-org/mlr3/jobs/421549350

Hence, all dependencies are missing in the check step because `remotes::install_deps()` is not called. No idea why this happens.

**Comment by pat-s** [comment]
Ok, it does call prepare but the installed packages (e.g. checkmate) are not found during R cmd build: https://travis-ci.org/mlr-org/mlr3/builds/421819019

Checkmate gets installed: https://travis-ci.org/mlr-org/mlr3/builds/421819019#L2074

Checkmate is not found: https://travis-ci.org/mlr-org/mlr3/builds/421819019#L5204

Maybe related to 7a0020f39be19c4a9442e16e3793149837087fa1?

**Comment by krlmlr** [comment]
Should work in the latest dev version of _tic_, sorry for the trouble. CC @edzer @tim-salabim.
