### ISSUE TITLE
Authentication issues during deployment

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#90]
https://travis-ci.org/mlr-org/mlr/jobs/427342503#L2616

Called `travis::use_travis_deploy()` several times to reinitiate the SSH keys but didn't help.

**Comment by krlmlr** [comment]
This is strange, it works just fine with the tic.package repo: https://travis-ci.org/krlmlr/tic.package/jobs/428176533#L1326

**Comment by krlmlr** [comment]
Could this be a travis.com issue?

**Comment by krlmlr** [comment]
Perhaps try removing the `id_rsa` travis var (multiple instances?), and repeat?

**Comment by krlmlr** [comment]
Do you see the deploy key on GitHub?

**Comment by pat-s** [comment]
Jep, also with desc "last used within the last week".

**Comment by krlmlr** [comment]
mlr builds seem fine now.
