### ISSUE TITLE
Add more color to the vignettes

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#91]
Requires writing text files with CSR and sourcing them into the report, and then convert with fansi. Low priority.

**Comment by krlmlr** [comment]
See `fansi::set_knit_hooks()`, it worked for me in similar situations.

**Comment by pat-s** [comment]
I tried but it is not so easy. The coloring also only applies for executed chunks as these get a different HTML class. It does not work for non-evaluated chunks.

We do not have that many tic example chunks that could make use of extensive coloring. 
Also runnign `dsl_get()` during `pkgdown_build_site()` errors even if `system.file()` is used to find `tic.R`.

I would vote to remote it from the v1.0.0 milestone.

**Comment by krlmlr** [comment]
Let's postpone.

**Comment by pat-s** [comment]
I think coloring non-evaluated code is still not possible using `fansi`? Maybe I am wrong.

I'll unassign myself for now. Not sure how important this point is in the end?

**Comment by pat-s** [comment]
Looking at the ropensci template right now, I think we have enough color.
