### ISSUE TITLE
Check if remotes and curl are already installed

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#97]
When initializing *tic* we currently always install *curl*  and *tic*.

We should check if the packages are already in the cache and only install if not.

```r
'if (!requireNamespace("remotes")) install.packages("remotes"); if (!requireNamespace("curl")) install.packages("curl"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
```

Also, what is `remotes::install_local(getwd())` doing effectively in this pipe?

**Comment by pat-s** [comment]
Should also be updated in the template: https://github.com/ropenscilabs/travis/blob/master/inst/templates/dot-travis.yml

**Comment by pat-s** [comment]
@krlmlr Can we apply this change to the `master` branch? Templates can follow later.

**Comment by krlmlr** [comment]
In this repo we're installing {tic} from local, not from GitHub. In the templates we still install from GitHub. `getwd()` should be `"."` .

{remotes} is small, I don't really mind reinstalling it every time, but we can check if you prefer. Can we use `remotes::install_cran()` to install {curl}?

**Comment by pat-s** [comment]
> In this repo we're installing {tic} from local, not from GitHub. In the templates we still install from GitHub. getwd() should be "." .

Ah, makes sense.

> {remotes} is small, I don't really mind reinstalling it every time, but we can check if you prefer. Can we use remotes::install_cran() to install {curl}?

It's small yes but anyhow it costs some time. On the other hand, all the `requireNamespace` checks clutter the travis yml. It's up to you :)

> Can we use remotes::install_cran() to install {curl}?

I guess so, then we'd only need `requireNamespace` once.

**Comment by pat-s** [comment]
I think we need `quietly = TRUE` for a robust approach.
