### ISSUE TITLE
Update step_rcmdcheck args

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#99]
We should provide the option to only run the check on a built tarball (possibly created externally by a direct R CMD build call). Can be done via argument `path` of `rcmdcheck()`.

Furthermore, `rcmdcheck()` updated the logic when to fail (notes, warnings etc). It's now `error_on = c()` which we should incorporate. Might complicate the checking and reporting to the user as we do it now with "warnings are found and warnings_are_errors is set" as everything is specified in one arg only rather than in single ones. 

(I started some experiments in the "rcmdcheck" branch.)

**Comment by pat-s** [comment]
Seems to work fine: 

https://github.com/mlr-org/mlr/blob/065088a08be18d6bd215590bc796720737f5e0f9/tic.R#L26-L31

The external tarball creation is a workaround for https://github.com/r-lib/rcmdcheck/issues/83.

But anyhow, we should give the user more options here (i.e. all options of `rcmdcheck()`) and update to the latest args.

I'll update the doc and then open a PR.

**Comment by krlmlr** [comment]
I'm not sure `step_rcmdcheck()` should be in charge of checking tarballs, this can be achieved with a regular `step_run_code()`.

Seems to be fixed, by and large.
